# Docker安装Server

version: '3'
services:
  xiaozhi-esp32-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports:
      # ws服务端
      - "8000:8000"
      # ota服务端
      - "8002:8002"
    volumes:
      # 配置文件目录
      - ./data:/opt/xiaozhi-esp32-server/data
      # 模型文件挂接，很重要
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
    deploy:
      resources:
        limits:
          cpus: '0.50'      # 限制最多使用0.5个CPU
          memory: 512M      # 限制最多使用512MB内存
        reservations:
          cpus: '0.25'      # 预留0.25个CPU
          memory: 256M      # 预留256MB内存